crudexample/urls.py
from django.contrib import admin  
from django.urls import path  
from agenda_contacto import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('contact', views.contact),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

agenda_contacto/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):  
    cid = models.CharField(max_length=20)  
    cnombre = models.CharField(max_length=100)  
    capellidos = models.CharField(max_length=100)  
    cemail = models.EmailField()  
    etelefono = models.CharField(max_length=15)  
    class Meta:  
        db_table = "contacto"

agenda_contacto/forms.py
from django import forms  
from agenda_contacto.models import Contacto  
class ContactoForm(forms.ModelForm):  
    class Meta:  
        model = Contacto
        fields = "__all__"

agenda_contacto/views.py
from django.shortcuts import render, redirect  
from agenda_contacto.forms import ContactoForm  
from agenda_contacto.models import Contacto  
# Create your views here.  
def contact(request):  
    if request.method == "POST":  
        form = ContactoForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ContactoForm()  
    return render(request,'index.html',{'forms':form})  
def show(request):  
    contactos = Contacto.objects.all()  
    return render(request,"show.html",{'contactos':contactos})  
def edit(request, id):  
    contacto = Contacto.objects.get(id=id)  
    return render(request,'edit.html', {'contacto':contacto})  
def update(request, id):  
    contacto = Contacto.objects.get(id=id)  
    form = ContactoForm(request.POST, instance = contacto)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'contacto': contacto})  
def destroy(request, id):  
    contacto = Contacto.objects.get(id=id)  
    contacto.delete()  
    return redirect("/show")  

agenda_contacto/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{contacto.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contacto Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cid" id="id_cid" required maxlength="20" value="{{ contacto.cid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nombre:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cnombre" id="id_cnombre" required maxlength="100" value="{{ contacto.cnombre }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Apellidos:</label>  
    <div class="col-sm-4">  
        <input type="text" name="capellidos" id="id_capellidos" required maxlength="100" value="{{ contacto.capellidos }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="cemail" id="id_cemail" required maxlength="254" value="{{ contacto.cemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Teléfono:</label>  
    <div class="col-sm-4">  
        <input type="text" name="etelefono" id="id_etelefono" required maxlength="15" value="{{ contacto.etelefono }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

agenda_contacto/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/contact">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contacto Id:</label>  
    <div class="col-sm-4">  
      {{ forms.cid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nombre:</label>  
    <div class="col-sm-4">  
      {{ forms.cnombre }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Apellidos:</label>  
    <div class="col-sm-4">  
      {{ forms.capellidos }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
      {{ forms.cemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Teléfono:</label>  
    <div class="col-sm-4">  
      {{ forms.etelefono }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

agenda_contacto/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Listado De Contactos</title>  
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body class="container mt-5">  
    <div class="flex text-center py-3">
        <h4 class="display-4">CRUD Agenda De Contacto</h4>
    </div>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Contacto ID</th>  
        <th>Contacto Nombre</th>  
        <th>Contacto Apellidos</th>  
        <th>Contacto Email</th>  
        <th>Contacto Teléfono</th>  
        <th>Acciones</th>  
    </tr>  
    </thead>  
  <tbody>  
{% for contacto in contactos %}  
    <tr>  
        <td>{{ contacto.cid }}</td>  
        <td>{{ contacto.cnombre }}</td>  
        <td>{{ contacto.capellidos }}</td>  
        <td>{{ contacto.cemail }}</td>  
        <td>{{ contacto.etelefono }}</td>  
        <td>  
            <a href="/edit/{{ contacto.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ contacto.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
  </tbody>  
</table>  
<br>  
<br>  
<center><a href="/contact" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  